# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' tav function
#' 
#' Stern F. (1964), Transmission of isotropic radiation across an
#' interface between two dielectrics, Appl. Opt., 3(1):111-113.
#' Allen W.A. (1973), Transmission of isotropic light across a
#' dielectric surface in two and three dimensions, J. Opt. Soc. Am.,
#' 63(6):664-666.
#' @references Feret et al. (2008), PROSPECT-4 and 5: Advances in the Leaf Optical
#' Properties Model Separating Photosynthetic Pigments, Remote Sensing of
#' Environment
#' 
#' @param(theta) Angle (in degrees!)
#' @param(ref) refractive index
#' @export
resHyp <- function(wl, R, mu, sigma) {
    .Call('_salt_resHyp', PACKAGE = 'salt', wl, R, mu, sigma)
}

